### ISSUE TITLE
Input gain settings are not saved

### ISSUE THREAD

**Issue by danieldickison** [moddevices/mod-duo-issues#27]
On 0.11.3:
- Go into left menu -> Volume and Gains -> Input 1 -> Fine Adjust -> set it at say -5 dB -> exit menu.
- Reboot
- Look in the same menu: gain has reset to 0 dB

**Comment by falkTX** [comment]
I can confirm the issue.
we'll either make it auto-save when you close the menu or add a new menu action to save the current mixer values.

**Comment by danieldickison** [comment]
Thanks for confirming. I think auto-save would be the way to go for this (I'm having a hard time thinking of use-cases where you wouldn't want it saved).

**Comment by falkTX** [comment]
Fixed on v0.15.0

**Comment by FPCmusic** [comment]
I still have this exact problem! Total random extatic behavior from the input gains. They reset at random to 0 or something else.

**Comment by metronomme** [comment]
Hello,
I don't know if this is the right place to post this, or even if this repository is being watched at all (I just found it googling for the Mod DUO, which I have just acquired second hand).
My DUO is on firmware 1.13 (the latest). However, the issue described here continues to happen: after I set input and output levels, if I switch off (by unplugging) and then switch on again, those settings are lost.
There is the "user profiles" feature, which doesn't help: each user profile reacts to the "override current user profile" action in a different way. If I save my gain settings on user profile A, levels get reset to -12db. If I override on user profile B, then levels get reset to -6 or something like that! Basically, completely random.

At the moment, everything works great, except that I need to spend a few minutes resetting the levels every time I switch the DUO on. Not a great user experience!

Thanks...
